#
#  eldoriaСhat by skippka;
#  main configuration.
#

# Настройки
settings:

  changename:
    #
    # Информация по использованию /changename
    info: '&fИспользование: &#9AD2F0/changename [имя] [фамилия] &f(&#9AD2F0/changename Фрид Гроули&f).'
    # Игрок использовал команду
    use: '&fВаш рп-никнейм был изменён. Чтобы снова его сменить, нужно подождать &#9AD2F02 часа&f.'
    # Имя или фамилия содержат запрещенный символ
    name-contains-forbidden-word: '&fВы хотели поставить себе &#9AD2F0запрещённый рп-никнейм&f.'
    # У игрока не закончился кулдаун на команду
    cooldown: '&fИзвините, Вы не можете использовать эту команду сейчас. Нужно подождать &#9AD2F0%time.'
    # Игрок ввел ник с неправильным размером.
    size: '&fВведённый Вами никнейм &#9AD2F0не соответствует размерам&f.'
    
    # Запрос на изменение ника
    request:
      # Включен ли режим запроса на изменение ника
      enable: true
      # Если нет администрации онлайн
      no-staff: '&fВы &#9AD2F0не можете &fотправить заявку на изменение ника. Администрация &#9AD2F0не в сети&f.'
      # Сообщение для администрации
      for-staff: '&#9AD2F0%nick &fхочет установить рп-никнейм &#9AD2F0%firstname %lastname&f.'
      # Сообщение для игрока
      message: '&fВаша заявка &#9AD2F0отправлена &fна рассмотрение администрации.'
      
      # Кнопки для администрации
      accept: ' &#9AD2F0[Подтвердить]'
      decline: '&#9AD2F0[Отклонить]'
      
    # Подтверждение запроса на смену ника
    accept:
      # Сообщение админу при подтверждении
      use: '&fВы подтвердили запрос на смену ника.'
      # Сообщение игроку
      target: '&fВам подтвердили запрос на смену ника.'
      # Если нет запроса
      no-request: '&fНет запроса для подтверждение.'
      
    # Отклонение запроса на смену ника
    decline:
      # Сообщение админу при отклонении
      use: '&fВы отклонили запрос на смену ника.'
      # Сообщение игроку
      target: '&fВам отклонили запрос на смену ника.'
      # Если нет запроса
      no-request: '&fНет запроса для отклонения.'
    
  # Допустимая длина рп-никнейма
  changename-size:

    max: 20 # максимум символов
    min: 10 # минимум символов
    
  # Задержка на смену никнейма
  cooldown: 120 # указывается в минутах
  
  # Запрещенные символы/слова в никнейме
  forbidden-words:
    - 'suck'
    - 'dick'
    
  # Команда /namereset
  namereset:
    #
    # Если игрок не устанавливал рп-никнейм
    no-change: '&fВы не устанавливали себе рп-никнейм.'
    # Использование команды
    use: '&fВы вернули себе обычный никнейм.'
    
  ### 
  ### День рождения
  ### 
    
  # Команда /rpage
  rpage:
    #
    # Информация по использованию /rpage
    info: '&fИспользование: &#9AD2F0/rpage [дд.мм.гггг]&f.'
    # Некорректный формат даты рождения
    incorrect: '&fВведён &#9AD2F0некорректный формат &fдаты рождения.'
    # При корректной установке дня рождения
    success: '&fВаша дата рождения: &#9AD2F0%birthday&f, ваш возраст: &#9AD2F0%years&f.'
    # Игрок уже установил дату рождения
    already: '&fУ вас уже установлена дата рождения.'
    
  # Команда /birthday
  birthday:
    #
    # Заполнитель даты рождения
    placeholder: "&#9AD2F0%date"
    
    # Информация по использованию /birthday
    use: '&fДата рождения: &#9AD2F0%birthday&f, возраст: &#9AD2F0%years&f.'
    # У игрока не указана дата рождения
    no-date: '&fДата рождения не указана.'
    # Объявление о дне рождения у игрока
    announce: '&f[&6Новости&f] Сегодня день рождения у игрока &#9AD2F0%player&f, поздравим его.'
    
    # Допустимый год даты рождения
    max: 2022 # максимальный год
    min: 1999 # минимальный год
    current: 2024 # текущий год
    # Сообщение при нарушение временных рамок
    time-error: '&fМаксимальный год - &#9AD2F02022&f, минимальный - &#9AD2F01999&f.'
    
  ### 
  ### Тюрьма
  ### 
    
  # Заключение в тюрьме
  arrest:
    #
    # Информация по использованию /arrest
    info: '&fИспользование: &#9AD2F0/arrest [ник] [тюрьма] [время] [причина].'
    # Игрок уже находится в тюрьме
    already: '&fИгрок &#9AD2F0уже находится &fв тюрьме'
    # Дистанция до игрока больше максимального значения
    high-distance: '&fРадиус от человека, которого Вы хотите арестовать, должен быть &#9AD2F0в размере 5-ти блоков&f, подойдите к преступнику ближе.'
    # Сообщение для полицейского
    send-arrest-policeman: '&fГражданин &#9AD2F0%name &fбыл посажен в &#9AD2F0тюрьму строгого режима&f на &#9AD2F0%time&f.'
    # Сообщение для нарушителя
    send-arrest-criminal: '&fВы были посажены в &#9AD2F0тюрьму строгого режима&f на &#9AD2F0%time&f, за хорошее поведение можно получить досрочное освобождение!'
    
  # Освобождение от тюрьмы
  letout:
    #
    # Информация по использованию /letout
    info: '&fИспользование: &#9AD2F0/letout [ник].'
    # Игрок не находится в тюрьме
    not-in-jail: '&fИгрок &#9AD2F0не находится &fв тюрьме.'
    # Игрок вышел из тюрьмы по окончанию срока
    letout-time: '&#9AD2F0%nick &fвышел из тюрьмы &#9AD2F0по окончанию срока&f.'
    # Сообщение для полицейского
    send-letout-policeman: '&fГражданин был &#9AD2F0освобождён&f.'
    # Сообщение для нарушителя
    send-letout-criminal: '&fВы &#9AD2F0вышли &fиз тюрьмы.'
    
  # Добавление времени игроку в тюрьме
  addtime:
    #
    # Информация по использованию /addtime
    info: '&fИспользование &#9AD2F0/addtime [Ник] [Время].'
    # Сообщение для полицейского
    send-addtime-policeman: '&fПреступник &#9AD2F0%nick &fтеперь будет сидеть в тюрьме на &#9AD2F0%time &fбольше.'
    # Сообщение для нарушителя
    send-addtime-criminal: '&fСрок в тюрьме &#9AD2F0был увеличен&f, тебе предстоит находиться в тюрьме на &#9AD2F0%time &fбольше.'
    
  # Ошибки
  errors:
    #
    # У игрока нет права на использование команды
    permission: '&fУ Вас &#9AD2F0недостаточно прав &fна выполнение данной команды.'
    # Игрок, который указан в аргументе %name - оффлайн
    offline: '&fУказанный игрок &#9AD2F0не в сети&f.'
    # Игрок использовует другие символы в аргументе %time
    number-exception: '&fВремя нужно указывать &#9AD2F0цифрами&f.'
    # Игрок пытается использовать запрещенную команду
    command-is-block: '&fДанную команду &#9AD2F0нельзя &fпрописывать, находясь в тюрьме.'
    # Тюрьма с указанным названием не найдена
    no-jail: '&fТюрьма не найдена.'
    
  # Команда /prison
  prison:
    #
    # Информация по командам тюрьмы
    help: |-
      &8 &8
      &8 &#9AD2F0/prison create [название] &8- &fсоздать тюрьму.
      &8 &#9AD2F0/prison delete [название] &8- &fудалить тюрьму.
      &8 &#9AD2F0/prison list &8- &fсписок существующих тюрем.
      &8 &8

    already-created: '&fТюрьма с таким названием &#9AD2F0уже существует&f.'
    create: '&fТюрьма была &#9AD2F0успешно &fсоздана.'
    delete: '&fТюрьма была &#9AD2F0успешно &fудалена.'
    list: '&fСписок существующих тюрем: &#9AD2F0<jails>&f.'
    
  # Команды /scprison и /slprison
  locations:
    #
    # Не указано название тюрьмы
    help: '&fУкажите название тюрьмы.'
    # Изменение точки входа в тюрьму
    scprison: '&fМесто для &#9AD2F0входа &fв тюрьму было &#9AD2F0успешно &fустановлено.'
    # Изменение точки выхода из тюрьмы
    slprison: '&fМесто для &#9AD2F0выхода &fиз тюрьмы было &#9AD2F0успешно &fустановлено.'
    
  # Запрещенные команды для игрока в тюрьме
  blocked-commands:
    - '/?'
    - '/about'
    
    ### 
    ### Интеграция с плагином LockSecurity - взлом дверей
    ### 
    
  # true - включение интеграции.
  # false - отключение интеграции.
  door-integration: false
  
  # Предмет отмычки
  key:
    # Айди предмета
    type: lever
    # Название предмета
    name: '&#9AD2F0Отмычка'
    # Описание предмета
    lore: []
    # Рецепт предмета
    craft:
      - 'air' # 1 слот
      - 'air' # 2 слот
      - 'air' # и т.д.
      - 'air'
      - 'lever'
      - 'air'
      - 'air'
      - 'air'
      - 'air'
    
  # Начало взлома
  breaking-start: '&fВы начали взлом.'
  # Игрок отошел от двери
  breaking-distance: '&fВзлом окончен &#9AD2F0неудачей&f. Вы отошли от двери.'
  # Неудачный взлом
  breaking-fail: '&fВзлом окончен неудачей.'
  # Удачный взлом
  breaking-success: '&fВзлом &#9AD2F0успешно &fпроизведён!'
    
  ### 
  ### Первый заход в игру
  ### 
    
  # true - включение этой системы.
  # false - отключение этой системы.
  first-join: true

  registration:
    #
    # Время обновления тайтла в тиках
    title-update: 50
    # Информация о вводе имени
    enter-name:
      title: '&fВведите ваше имя'
      subtitle: '&fФормат: &#9AD2F0Имя Фамилия&f, пример: &#9AD2F0Иван Иванов'
    # Информация о вводе даты рождения
    enter-age:
      title: '&fВведите вашу дату рождения'
      subtitle: '&fФормат: &#9AD2F0дд.мм.гггг&f, пример: &#9AD2F022.12.2000'
    # Информация о вводе пола
    enter-sex:
      title: '&fВведите ваш пол'
      subtitle: '&fФормат: &#9AD2F0Мужской или Женский&f'
      
    # Некорректно введена информация
    incorrect-format: '&#9AD2F0Введен &#9AD2F0неверный формат &fданных.'
    # Список разрешенных команд во время регистрации
    commands-whitelist:
      - '/login'
      - '/l'
      - '/reg'
      - '/register'
    # Регистрация персонажа завершена
    end: '&fВы &#9AD2F0завершили &fпервичную регистрацию. Ваши данные: &#9AD2F0%displayname&f, &#9AD2F0%birthday&f.'
    # Сообщение об подтверждении регистрации
    confirmation:
      header: '&fВы: &#9AD2F0%displayname&f, дата рождения: &#9AD2F0%birthday&f. Закончить регистрацию?'
      accept: '&#9AD2F0[подтвердить]'
      reset: '&#9AD2F0[начать заново]'
    
  ### 
  ### Система знакомств
  ### 

  friends:
    enable: false
    #
    # Задержка между запросами в друзья
    # Указывается в секундах
    cooldown: 60
    gui:
      request:
        # Название инвентаря
        title: '&8Запрос в друзья'
        # Название предмета подтверждение запроса
        accept: '&#9AD2F0Принять запрос'
        # Название предмета отклоняющий запрос
        decline: '&#9AD2F0Отклонить запрос'
        
      friend:
        # Название инвентаря
        title: '&8%displayname'
        # Название предмета, удаляющего игрока из друзей
        remove: '&#9AD2F0Удалить из друзей'
      
    # Запрос в друзья
    request:
      send: '&fВы отправили &#9AD2F0%stranger &fпредложение знакомства.'
      accept:
        accepter: '&fВы приняли предложение &#9AD2F0%stranger&f, теперь он: &#9AD2F0%displayname.'
        target: '&#9AD2F0%stranger &fпринял ваше предложение, теперь он: &#9AD2F0%displayname.'
      decline:
        decliner: '&fВы отклонили предложение &#9AD2F0%stranger.'
        target: '&#9AD2F0%stranger &fотклонил ваше предложение.'
    
    # Удаление из друзей
    remove:
      remover: '&fВы удалили из друзей &#9AD2F0%displayname&f, теперь он: &#9AD2F0%stranger'
      target: '&#9AD2F0%displayname &fудалил вас из друзей, теперь он: &#9AD2F0%stranger.'
    
    # Сообщение о задержке
    cooldown-message: '&#9AD2F0Вы не можете отправлять запрос знакомства одному игроку &#9AD2F0так часто&f.'
    
    # Имя незнакомца
    stranger-name: 'Гражданин #%index'
    
  ### 
  ### Настройка команд
  ### 
    
  # Радиусы отображения в чате
  radiuses:

    me: 5 # действие от 1-го лица
    do: 5 # описание ситуации от 3-го лица
    try: 5 # действие 50/50 (удачно/неудачно)
    todo: 5 # описание ситуации + слова игрока
    nrp: 5 # внеигровой локальный чат

    coin: 5 # орёл или решка
    cube: 5 # бросок кубика
    roll: 5 # рулетка чисел

    wh: 5 # шёпот
    sh: 5 # крик
    
  # формат отображения в чате
  formats:

    me: ' &#9AD2F0* &f%name &7%text'
    do: '&7%text &8- &f%name'
    try: '&f%name &7%text &8- &7[%action&7]'
    todo: '&7%prefix - сказал %name, %suffix.'
    nrp: '&7(( &8%name -> &#9AD2F0%text&7 ))'

    gme: '&#9AD2F0* &f%name &7%text'
    gdo: '&7%text &8- &f%name'
    gtry: '&f%name &7%text &8- &7[%action&7]'

    coin: '&7%name бросил монетку (%result)'
    cube: '&7%name подбросил кубик (%result) '
    roll: '&f%displayname &fимеет шанс &#9AD2F0%result/100'

    wh: '&7%name кричит: "%text"'
    sh: '&7%name шепчет: "%text"'
    
  # Информация по использованию команд
  me:
    # Информация по использованию /me
    info: '&7Использование &#9AD2F0/me [Текст]'
  do:
    # Информация по использованию /do
    info: '&7Использование &#9AD2F0/do [Текст]'
  try:
    # Информация по использованию /try
    info: '&7Использование &#9AD2F0/try [Текст]'
  todo:
    # Информация по использованию /todo
    info: '&7Использование /todo [текст] * [суффикс]'
  nrp:
    # Информация по использованию /nrp
    info: '&7Использование &#9AD2F0/nrp [Текст]'

  gme:
    # Информация по использованию /gme
    info: '&7Использование &#9AD2F0/gme [Текст]'
  gdo:
    # Информация по использованию /gdo
    info: '&7Использование &#9AD2F0/gdo [Текст]'
  gtry:
    # Информация по использованию /gtry
    info: '&7Использование &#9AD2F0/gtry [Текст]'

  wh:
    # Информация по использованию /wh
    info: '&7Использование /wh [текст]'
  sh:
    # Информация по использованию /sh
    info: '&7Использование /sh [текст]'